A BUG was found that we get error while installing the NVD Tool
facebookincubator/nvdtools pull request #194
Opened 2022-09-13 18:15 UTC by aravindb26

Hi team,
Hope all going well

I have found a BUG that we get an error while installing the NVD Tool. It shows the Impact when small developers want to Install It and test your tool. In these cases, they face the issue and leave it without testing. And also a loss for Facebookincubator

Thank You :)

2022-09-16 15:27 UTC, ImanolBarba requested changes
Hi, thanks for raising this issue.

As of go 1.18, `go get` will in fact not install the binaries

Could you please add a line indicating that this command is for users of go 1.17 and above?

Thanks

2022-09-16 15:51 UTC, aravindb26 reviewed
Added the line

2022-09-16 15:54 UTC, aravindb26 commented
> this command is for users of go 1.17 and above

Hi, @ImanolBarba added the line as you said :)

2022-09-18 17:35 UTC, aravindb26 commented
@ImanolBarba Have you looked that I have made changes as you asked?

2022-09-20 10:35 UTC, ImanolBarba commented
I would prefer if you left the original line, then *added* the go 1.17 line below with the comment prefacing it.

Thanks!

2022-09-20 10:36 UTC, ImanolBarba requested changes
As mentioned, preserve the original line please

2022-09-20 10:46 UTC, aravindb26 commented
> 

Which line i should add? Can you screenshot it? I didn't understood what you want

2022-09-20 10:49 UTC, aravindb26 reviewed
Is it good now @ImanolBarba

2022-09-20 11:58 UTC, ImanolBarba commented on README.md
> +## This command is for users of go 1.17 and above
This should be before the go install line

2022-09-20 11:58 UTC, ImanolBarba requested changes
See comments

2022-09-20 13:17 UTC, aravindb26 commented
> See comments

Yeah check it, already done that

2022-09-23 10:14 UTC, ImanolBarba commented
I don't see the changes I suggested applied, it should read like:

```bash
go get github.com/facebookincubator/nvdtools/...

## This command is for users of go 1.17 and above
go install github.com/facebookincubator/nvdtools/...@latest
```

2022-09-23 11:38 UTC, aravindb26 reviewed
Already changed

2022-10-01 14:02 UTC, ImanolBarba commented
Changes are still not applied, I suggested you format the commands differently because the way it is now it's not clear how users of one version should run the commands from another version.

We'll update the README.

2022-10-01 14:02 UTC, closed without merging